<h1 style = "color:Brown">Objectives</h1>

### 1. Loading data.
### 2. Checking for missing values.
### 3. Splitting the data in to train set and test set.




<h2 style = "color:green">Loading Data</h2>

In [2]:
# Load the data from sklearn.datasets - load_iris(), load_diabetes(), load_digits(), load_linnerud(), load_wine(), load_breast_cancer()
from sklearn.datasets import load_iris
dataset=load_iris()
print(type(dataset))
print()

X=dataset.data
print(X.shape)
print(type(X))
print(X[0:5])
print(dataset.feature_names)
print()

Y=dataset.target
print(type(Y))
print(Y[145:150])
print(dataset.target_names)


<class 'sklearn.utils._bunch.Bunch'>

(150, 4)
<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

<class 'numpy.ndarray'>
[2 2 2 2 2]
['setosa' 'versicolor' 'virginica']


In [3]:
#Loading the dataset as separate input and output numpy arrays as ndobjects
X,y=load_iris(return_X_y=True)
print(type(X))
print(X[0:6])
print()

print(type(y))
print(Y[0:6])


<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]

<class 'numpy.ndarray'>
[0 0 0 0 0 0]


In [3]:
# Parameter as_frame=True returns the data as a dataframe.

X,y=load_iris(return_X_y=True,as_frame=True)
print(type(X))
print(X[0:6])
print()

print(type(y))
print(y[0:6])

<class 'pandas.core.frame.DataFrame'>
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4

<class 'pandas.core.series.Series'>
0    0
1    0
2    0
3    0
4    0
5    0
Name: target, dtype: int32


In [1]:
# Load the data from external flat file - use pandas.read_csv() or pandas.read_excel()
import pandas as pd
df1=pd.read_csv("Test.csv")
print(df1.shape)
print(df1.columns)
print(df1.head(4))


(3, 3)
Index(['CreditScore', 'Age', 'Exited'], dtype='object')
   CreditScore  Age  Exited
0            2    3       1
1            3    4       0
2            5    6       2


<h2 style = "color:green">pandas.isna(object)</h2>

### Detects missing values.
### Returns a boolen object of same size.
### None and np.NaN are mapped True values. Everything else gets mapped to False values.

In [4]:
df1.isna().sum()

CreditScore    0
Age            0
Exited         0
dtype: int64

In [5]:
x=df1.drop('Exited',axis=1)
y=df1["Exited"]
print(x.head())
print()
print(y.head())

   CreditScore  Age
0            2    3
1            3    4
2            5    6

0    1
1    0
2    2
Name: Exited, dtype: int64


In [6]:
# Split the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)



(2, 2)
(2,)
(1, 2)
(1,)


#### We can use random_state keyword argument to get same set of training and testing samples.

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=15)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(2, 2)
(2,)
(1, 2)
(1,)
